### ISSUE TITLE
"对长文本进行分页渲染的思路"代码没有了？

### ISSUE THREAD

**Issue by wonderffee** [Lessica/ShanbayIntern#1]
不好意思在这里开一个issue，搜到了你的这篇文章：https://82flex.com/p/long-attributed-text-for-pagination/ ，文末提供的链接https://github.com/Lessica/StoneRead-Txt-Core 打开是404，能更新一下吗

**Comment by Lessica** [comment]
Issue 不是用来给你干这种事情的
